MakeARev/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from rest_framework import routers
from django.contrib.auth import views as auth_views
from django.urls import path, include

from MakeARev.viewsets import CustomUserViewSet, BrandViewSet, CategoryViewSet, ProductViewSet
from reviews.forms import LoginForm, ChangePasswordForm, ResetPasswordForm, PasswordSetForm

router = routers.DefaultRouter()
# router.register(r'users', CustomUserViewSet)
# router.register(r'brands', BrandViewSet)
# router.register(r'categories', CategoryViewSet)
# router.register(r'products', ProductViewSet)


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('reviews.urls')),
    path("accounts/login/", auth_views.LoginView.as_view(form_class=LoginForm), name="login"),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(form_class=ChangePasswordForm),
         name='password_change'),
    path("accounts/password_reset/", auth_views.PasswordResetView.as_view(form_class=ResetPasswordForm),
         name="password_reset"),
    path("accounts/reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(form_class=PasswordSetForm),
         name="password_reset_confirm", ),
    path('accounts/', include('django.contrib.auth.urls')),

    path('api-auth/', include('rest_framework.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('api/', include(router.urls)),
    prefix_default_language=False,
)

reviews/urls.py
from django.urls import path

from reviews import views

urlpatterns = [
    path('', views.homepage_view, name='home'),

    path('product/add/', views.ProductCreateView.as_view(), name='product-add'),
    path('product/', views.ProductListView.as_view(), name='product_list'),
    path('brand/', views.BrandListView.as_view(), name='brand_list'),
    path('category/', views.CategoryListView.as_view(), name='category_list'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('brand/<int:pk>/', views.BrandDetailView.as_view(), name='brand_details'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category_details'),
    path('review/create/', views.ReviewCreateView.as_view(), name='review_create'),
    path('create-user/', views.UserCreateView.as_view(), name='create-user'),
]

reviews/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import Avg
from django.utils import timezone


class CustomUser(AbstractUser):
    phone_number = models.CharField(max_length=11, unique=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}"


class Brand(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/products/')

    def __str__(self):
        return f"{self.name}"

    def average_rating(self):
        rating = Review.objects.filter(product=self).aggregate(Avg('grade'))
        print(f'rating={rating} product={self.name}')
        return int(rating['grade__avg']) if rating['grade__avg'] is not None else None


class Review(models.Model):
    text = models.TextField()
    grade = models.PositiveIntegerField()
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.product} {self.grade}"

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include 'navbar.html' %}
<div class="p-0 m-0 d-flex justify-content-center">
    {% block content %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

templates/brand_details.html
{% extends 'base.html' %}

{% block title %}{{ brand.name }}{% endblock %}

{% block content %}
    {% url 'brand-update' brand.id as update_url %}
    {% include 'partials/name_and_product_block.html' with title=brand.name products=brand.product_set.all %}
{% endblock %}

templates/brandlist.html
{% extends 'base.html' %}

{% block title %}Brand List{% endblock %}

{% block content %}
    <div class="col-12">
        {% if request.user.is_superuser %}
            <div class="row">
                <div class="col-xl-2 col-md-4 col-6 ">
{#                    <a class="btn btn-success col-12 mx-2" href="{% url 'brand-add' %}" title="Create brand">Create Brand</a>#}
                </div>
            </div>
        {% endif %}


        {% include 'partials/name_and_brands_block.html' with title='All Brands' empty_text='There are no brands here yet.' %}
    </div>
{% endblock %}

templates/category_details.html
{% extends 'base.html' %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    {% url 'brand-update' category.id as update_url %}
    {% include 'partials/name_and_product_block.html' with title=category.name products=category.product_set.all %}
{% endblock %}

templates/categorylist.html
{% block title %}Category List{% endblock %}

{% block content %}
    <div class="col-12">
        {% if request.user.is_superuser %}
            <div class="row">
                <div class="col-xl-2 col-md-4 col-6 ">
{#                    <a class="btn btn-success col-12 mx-2" href="{% url 'category-add' %}" title="Create category">Create Category</a>#}
                </div>
            </div>
        {% endif %}


        {% include 'partials/name_and_category_block.html' with title='All Categories' empty_text='There are no categories here yet.' %}
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Homepage{% endblock %}

{% block content %}
    <div class="m-0 p-0">
        {% include 'partials/name_and_product_block.html' with products=latest_products title='Latest products' bg_color='#F5D3E5' %}
        {% include 'partials/name_and_product_block.html' with products=popular_products title='Best reviewed products' bg_color='#F5D3EF' %}
        {% include 'partials/name_and_product_block.html' with products=least_popular_products title='Worst reviewed products' bg_color='#F4D3F5' %}
    </div>
{% endblock %}

{#F5D3E5#}
{##E5A5C7#}
{##E5A5DA#}
{##DAA5E5#}

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">MakeARev</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
{#                <li class="nav-item">#}
{#                    <a class="nav-link active" aria-current="page" href="#">Home</a>#}
{#                </li>#}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'product_list' %}">Products</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url 'category_list' %}" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Category
                    </a>
                    <ul class="dropdown-menu">
                        {% for category in categories %}
                            <li><a class="dropdown-item"
                                   href="{% url 'category_details' category.pk %}">{{ category.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url 'brand_list' %}" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Brand
                    </a>
                    <ul class="dropdown-menu">
                        {% for brand in brands %}
                            <li><a class="dropdown-item" href="{% url 'brand_details' brand.pk %}">{{ brand.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                    {% if request.user.is_authenticated %}
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button class="nav-link" type="submit">Logout, {{ request.user.username }}</button>
                    </form>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'password_change' %}">Change password</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'create-user' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'password_reset' %}">Reset password</a>
                    </li>
                {% endif %}
                {#                <li class="nav-item">#}
                {#                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>#}
                {#                </li>#}
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

templates/productcreate.html
{% extends 'base.html' %}

{% block title %}Product create{% endblock %}

{% block content %}
    <div class="col-md-6 col-12">
        <h1>Product create</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success form-control">Submit</button>
        </form>
    </div>
{% endblock %}

templates/productdetails.html
{% extends 'base.html' %}
{% load static %}

{% block name %}Product detail {{ product.name }}{% endblock %}

{% block content %}
    <div class="col-xl-6 col-lg-9 col-12">
        <div class="col-12 row">
            <div class="col-lg-6 col-12">
                <img src="{{ product.image.url }}" alt="product image" class="col-12">
            </div>
            <div class="col-lg-6 col-12">
                <h1>
                    <p>{{ product.name }}</p>
                </h1>
                <p><a href="{% url 'category_details' product.category.pk %}"> {{ product.category }} </a></p>
                By<p><a href="{% url 'brand_details' product.brand.pk %}">{{ product.brand }}</a></p>
{#                Main review#}
        </div>
        <div class="col-12">
            <form action="{% url 'review_create' %}?product={{ product.id }}" method="post">
                {% csrf_token %}
                <input type="hidden" name="product" value="{{ product.id }}">
                {{ review_form.as_p }}
                <button type="submit" class="btn btn-success">Create review</button>
            </form>
        </div>

        <div class="col-12">
            {% for review in product.review_set.all %}
                <div>
                    <img src="{% static 'icons/user.png' %}" alt="user" height="24" width="24">
                    {{ review.user.get_full_name }}
                    {% include 'partials/stars.html' with grade=review.grade %}
                </div>
                <div>
                    <p>
                         {{ review.text }}
                    </p>
                    <p>
                        {{ review.date }}
                    </p>
                </div>
            {% endfor %}

        </div>

    </div>
{% endblock %}

templates/productlist.html
{% extends 'base.html' %}

{% block title %}Product List{% endblock %}

{% block content %}
    <div class="col-12">
        {% if request.user.is_superuser %}
            <div class="row">
                <div class="col-xl-2 col-md-4 col-6 ">
                    <a class="btn btn-success col-12 mx-2" href="{% url 'product-add' %}" title="Create product">Create Product</a>
                </div>
            </div>
        {% endif %}


        {% include 'partials/name_and_product_block.html' with title='All Products' empty_text='There are no products here yet.' %}
    </div>
{% endblock %}

templates/review_create_view.html
{% extends 'base.html' %}

{% block title %}Reate review{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create review</button>
    </form>
{% endblock %}

templates/user_create.html
{% extends 'base.html' %}

{% block title %}Create User{% endblock %}

{% block content %}
    <div class="col-md-6 col-12">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="Submit" class="btn btn-success form-control">Submit</button>
        </form>
    </div>
{% endblock %}